### ISSUE TITLE
[Bug]: Object reference not set to an instance of an object when using Shiny.Push.FirebaseMessaging 2.5.x with Prism.DryIoc.Forms

### ISSUE THREAD

**Issue by appimpact** [shinyorg/shiny#1033]
### Component/Nuget

Push - Native (Shiny.Push)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Mac Catalyst
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [X] Android 12

### What platform(s) are effected?

- [ ] MAUI
- [ ] Xamarin Native
- [X] Xamarin Forms

### Steps To Reproduce

1. Install Shiny, Shiny.Jobs and Shiny.Push.FirebaseMessaging packages
2. Override CreateServiceProvider method in ShinyStartup to configure reuse of Prism service registrations
3. Call .UseFirebaseMessaging in ConfigureServices method of ShinyStartup

Sample:
https://github.com/App-Impact-Labs/ISSUE-ShinyPrismIntegrationException

### Expected Behavior

Application should start normally as it did with Shiny 2.4.x libraries.

### Actual Behavior

Application crashes on start when upgraded from Shiny 2.4.x to Shiny 2.5.x libraries.
As soon as .UseFirebaseMessaging is used, error starts to occur.

### Exception or Log output

[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.Forms.Platform.Android.AppLinks.dll
**System.NullReferenceException:** 'Object reference not set to an instance of an object.'

### Code Sample

Example can be found on the following repository:

https://github.com/App-Impact-Labs/ISSUE-ShinyPrismIntegrationException

If you comment out the following line in Startup.cs:

`services.UseFirebaseMessaging<DefaultPushDelegate>();`

... Android app will start without any issues.

### Code of Conduct

- [X] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
It isn't an issue with Shiny directly since Shiny is getting through it's startup process.  It could be a mixture of lib versions going wrong somewhere as it even looks post-Prism startup.  It gets all the way to the page constructor. 

I've played with this a bit in the samples, but I'm not willing to take this as a bug since it is very external to this project.  I'll toy around with this in the samples a bit to see if I can't get more info for another project.

**Comment by appimpact** [comment]
@aritchie  If you revert Shiny dependencies on example project to 2.4.3.3024 or any earlier versions, it will start to work.
Issue started to occur with version 2.5.1 and continued to exist since then on every next version.

One unusual change that we have noticed is this:
1) Xamarin.Forms has following dependency scope:
[Xamarin.AndroidX.Lifecycle.LiveData](https://www.nuget.org/packages/Xamarin.AndroidX.Lifecycle.LiveData/) (>= 2.3.1.1 && < 2.4.0)
2) You have following dependency scope on Shiny.Jobs:
[Xamarin.AndroidX.Work.Runtime](https://www.nuget.org/packages/Xamarin.AndroidX.Work.Runtime/) (>= 2.7.1.1 && < 2.8.0)
3) Xamarin.AndroidX.Work.Runtime has following dependency scope:
[Xamarin.AndroidX.Lifecycle.LiveData](https://www.nuget.org/packages/Xamarin.AndroidX.Lifecycle.LiveData/) (>= 2.4.0.1)

There is no way to satisfy these dependency requirements properly as Xamarin.Forms latest version supports Xamarin.AndroidX.Lifecycle.LiveData up to version 2.4.0 while dependency chain of Shiny.Jobs requires same library to be at version >= 2.4.0.1 .

Also, if you comment out this code entirely:

```
public override IServiceProvider CreateServiceProvider(IServiceCollection services)
        {
            ContainerLocator.SetContainerExtension(() => new DryIocContainerExtension());

            IContainer container = ContainerLocator.Container.GetContainer();

            DryIocAdapter.Populate(container, services);

            return container.GetServiceProvider();
        }
```


... application will start normally.

**Comment by aritchie** [comment]
> If you revert Shiny dependencies on example project to 2.4.3.3024 or any earlier versions, it will start to work.
Issue started to occur with version 2.5.1 and continued to exist since then on every next version.

So switch back to 2.4 if it works for you.  I bumped everything to android 12 as of 2.5. 

> There is no way to satisfy these dependency requirements properly as Xamarin.Forms latest version supports Xamarin.AndroidX.Lifecycle.LiveData up to version 2.4.0 while dependency chain of Shiny.Jobs requires same library to be at version >= 2.4.0.1 .

The XF team is aware of this and they need to get caught up with AndroidX deps so the rest of the things like firebase continue to work.  I push forward AX dependencies regardless of where XF is because I have other needs to that require updates.

> Also, if you comment out this code entirely:

This is an integration totally separate to Shiny.  The fact is that the "out-of-box" stuff does work and I'm not willing to support beyond that.  As it is, I don't even think the issue is with Prism either.  I think there is a mashing of AX lib versions being forced and XF itself is crashing.

**Comment by aritchie** [comment]
This is why I will never support every integration.  The bug is NOT shiny.  It is with the way dryioc handles optional parameters.


[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentNullException: Value cannot be null.
[mono-rt] Parameter name: AppId
[mono-rt]   at Shiny.Push.FirebaseConfig.AssertValid () [0x0000e] in C:\dev\shinyorg\samples\submodules\shiny\src\Shiny.Push.Common\Platforms\Android\FirebaseConfig.cs:11 
[mono-rt]   at Shiny.Push.NativeAdapter..ctor (Shiny.IPlatform platform, Microsoft.Extensions.Logging.ILogger`1[TCategoryName] logger, Shiny.Stores.IKeyValueStore settings, Shiny.Push.FirebaseConfig config) [0x0000f] in C:\dev\shinyorg\samples\submodules\shiny\src\Shiny.Push.Common\Platforms\Android\NativeAdapter.cs:35 
[mono-rt]   at (wrapper managed-to-native) System.Reflection.RuntimeConstructorInfo.InternalInvoke(System.Reflection.RuntimeConstructorInfo,object,object[],System.Exception&)
[mono-rt]   at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00005] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:936 
[mono-rt]   at DryIoc.Interpreter.TryInterpretAndUnwrapContainerException (DryIoc.IResolverContext r, FastExpressionCompiler.LightExpression.Expression expr, System.Boolean useFec, System.Object& result) [0x0002f] in /_/src/DryIoc/Container.cs:2868 
[mono-rt]   at DryIoc.Factory.ApplyReuse (FastExpressionCompiler.LightExpression.Expression serviceExpr, DryIoc.Request request) [0x00157] in /_/src/DryIoc/Container.cs:10340 
[mono-rt]   at DryIoc.Factory.GetExpressionOrDefault (DryIoc.Request request) [0x00315] in /_/src/DryIoc/Container.cs:10242 
[mono-rt]   at DryIoc.ReflectionFactory.CreateExpressionOrDefault (DryIoc.Request request) [0x0033c] in /_/src/DryIoc/Container.cs:10917 
[mono-rt]   at DryIoc.Factory.GetExpressionOrDefault (DryIoc.Request request) [0x002c6] in /_/src/DryIoc/Container.cs:10228 
[mono-rt]   at DryIoc.Container.ResolveAndCache (System.Int32 serviceTypeHash, System.Type serviceType, DryIoc.IfUnresolved ifUnresolved) [0x0008f] in /_/src/DryIoc/Container.cs:391 
[mono-rt]   at DryIoc.Container.DryIoc.IResolver.Resolve (System.Type serviceType, DryIoc.IfUnresolved ifUnresolved) [0x0011c] in /_/src/DryIoc/Container.cs:356 
[mono-rt]   at DryIoc.Container.System.IServiceProvider.GetService (System.Type serviceType) [0x00000] in /_/src/DryIoc/Container.cs:307 
[mono-rt]   at Shiny.Infrastructure.StartupModule.Get (Microsoft.Extensions.DependencyInjection.ServiceDescriptor service) [0x00017] in C:\dev\shinyorg\samples\submodules\shiny\src\Shiny.Core\Infrastructure\StartupModule.cs:103 
[mono-rt]   at Shiny.Infrastructure.StartupModule.DoStartups (System.Collections.Generic.IList`1[T] singletons) [0x0003f] in C:\dev\shinyorg\samples\submodules\shiny\src\Shiny.Core\Infrastructure\StartupModule.cs:89 
[mono-rt]   at Shiny.Infrastructure.StartupModule.Bind (Microsoft.Extensions.DependencyInjection.IServiceCollection services) [0x00034] in C:\dev\shinyorg\samples\submodules\shiny\src\Shiny.Core\Infrastructure\StartupModule.cs:55 
[mono-rt]   at Shiny.Infrastructure.StartupModule.Start (Microsoft.Extensions.DependencyInjection.IServiceCollection services) [0x00008] in C:\dev\shinyorg\samples\submodules\shiny\src\Shiny.Core\Infrastructure\StartupModule.cs:36 
[mono-rt]   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021 
[mono-rt]   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:36 
[mono-rt]   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36 
[mono-rt]   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-31/mcw/Java.Lang.IRunnable.cs:84 
[mono-rt]   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V (_JniMarshal_PP_V callback, System.IntPtr jnienv, System.IntPtr klazz) [0x00005] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:22 
[mono-rt]   at (wrapper native-to-managed) Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(intptr,intptr)

**Comment by appimpact** [comment]
Is it too much to ask to just add = null on optional dependency so that this gets resolved?

**Comment by aritchie** [comment]
The null is already there.  I'm not going to ship a release just for this one thing.  I'll look into it for the next minor release.
