### ISSUE TITLE
Please add the usage of payload to the readme of Sample.Push.Maui project.

### ISSUE THREAD

**Issue by masatoru** [shinyorg/shiny#1172]
### Summary

When testing `Sample.Push.Maui` with Azure Notification Hubs, I found that to receive messages with `DidReceiveRemoteNotification` when the iOS app is active, the payload **MUST** have a `content-available: 1`.
So it would be great if you could add this point to the readme.

Thnaks.

### API Changes

none

### Intended Use Case

none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Please review the code of conduct before posting stuff in the future.  https://github.com/shinyorg/shiny/blob/master/.github/CODE_OF_CONDUCT.md

I don't take requests for docs because I'm a one man show.  If people want something, they can submit a PR for it.  I also don't like to shadow what's in the OS documentation.
