### ISSUE TITLE
[Feature Request]: Support Push notifications for iOS Simulator

### ISSUE THREAD

**Issue by nielscup** [shinyorg/shiny#1460]
### Summary

iOS Simulator also supports push notifications. But the PushManager prevents us from registering for PushNotifications: `if (AppleExtensions.IsSimulator)`

### API Changes

remove `if (AppleExtensions.IsSimulator)` in PushManager 

### Intended Use Case

Test push notifications on iOS simulator

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
The problem is that people assume push is actually working.  APNS is not available on simulators, only the ability to test payloads against the app.  This has been a constant source of pain to support even if I document.  

You technically only need the notification permission from iOS.  You can do this with an compiler ifdef yourself and ignore RequestAccess while on the simulator
