### ISSUE TITLE
Geofencing fails when HTTP Post added

### ISSUE THREAD

**Issue by RobbieNesmith** [shinyorg/shiny#166]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [x] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [x] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.503
## Version of OS(s) listed above with issue
Android 9 (Galaxy S8)

## Steps to Reproduce
1. Clone shinysamples repository
2. Add in a job that makes a request to a server that gets initiated by a geofence trip. [Code](https://github.com/RobbieNesmith/shinysamples/pull/1)
3. Enable background ANR notifications (Developer Options > Apps > Show background ANRs)
4. Create some geofences and exercise the app

## Expected Behavior
A slack message is sent whenever a geofence is triggered, Appcenter crashes should log any errors if something goes wrong

## Actual Behavior
App will become unresponsive in the background after a while and does not report anything to Appcenter. I have been working with @dahlbyk on a client project where we see this issue, and it still happens when we copied a simplified version of our logic to the shiny sample app.

**Comment by aritchie** [comment]
I can't speak for any appcenter setup too much - you likely won't see those messages until it has a chance to sync itself.  You're also doing this in an incredibly odd way.

You should store the geofence results to a database and use a single job (that is in control of itself - don't force run it) that has a chance to run based on network connectivity, let it push the results.  There could be any number of issues going on here - too many jobs being queued, etc.  

Unfortunately, there isn't anything serviceable as far as shiny itself being an issue.  I use the geofencing/job setup in several places without issue.  You have to give me crashes or some sort of memory leak in order to be able to provide any assistance

**Comment by RobbieNesmith** [comment]
I have updated my [modifications to the example code](https://github.com/RobbieNesmith/shinysamples/pull/1) with your suggestions. It seems to work at first, but the next day the HTTP post triggers multiple times. A few days later the app got locked in a crash loop and I had to uninstall it. During this crash loop nothing shows up in the Appcenter crash reports. I saw the same behavior when I integrated it with my app. I have attached a screenshot of the Slack message history with my webhook. All grouped messages have the same timestamp to the second.

As a side note, I have been only developing on Android but I intend to release to iOS as well. Based on your blog posts, it looks like this is the only way to send background messages on iOS since it piggybacks on the Background Fetch. When it was working on Android, there was a ~10-15 minute delay when sending the messages to the server. Is this the best performance that I can expect? Ideally the server would receive the geofence events as the user enters or leaves.

![GeofenceExample](https://user-images.githubusercontent.com/6155690/70455604-39690800-1a72-11ea-9a58-5dc31a0f23b1.png)

**Comment by aritchie** [comment]
While I appreciate that you are trying to use Shiny, I still don't have an actionable bug here (no exceptions/stack traces or small repos that show ONLY shiny code issues).  You say you have a crash loop - with what?  What's the exception?  Why is it stuck in a loop?!?!  How do you know it is stuck in a loop?  I need these details.  I don't usually flip through code that has external dependencies and logic.  

The fact that the geofence is posting multiple times is likely due to the fact that it is taking too long to post the data and you are never updating your data NOT to post again.  There is a cancellation token passed into the job that you need to watch.  

I do offer consulting if needed.

**Comment by aritchie** [comment]
Fill in the TODO's below - this will fix most/all of what you are seeing.  Any crashes won't be logged by AppCenter likely until the app is back in the foreground.  They have their own sync logic.  Please remove anything to do with appcenter in any future filings.

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AppCenter.Analytics;
using Microsoft.AppCenter.Crashes;
using Samples.Models;
using Shiny;
using Shiny.Jobs;
using Shiny.Locations;
using Shiny.Notifications;
using Shiny.Net;

namespace Samples.ShinyDelegates
{
    public class GeofenceBackgroundJob : IJob, IGeofenceDelegate
    {

        readonly CoreDelegateServices services;
        readonly IConnectivity connectivity;


        public LocationDelegates(CoreDelegateServices services, IConnectivity connectivity)
        {
            this.services = services;
            this.connectivity = connectivity;
        }

        public Task OnStatusChanged(GeofenceState newStatus, GeofenceRegion region) 
        {
            // TODO: store it here first with IsReported = 0
            if (this.connectivity.IsInternetAvailable()) 
            {
                try 
                {
                    // TODO: send to your slack channel
                    // update IsReported = 1
                }
                catch {} // who cares
            }
        }


        // TODO: you should only retry a send X amount of times
        // TODO: you should delete successful sends or something will need to clean them up
        public async Task<bool> Run(JobInfo jobInfo, CancellationToken cancelToken)
        {            
            Analytics.TrackEvent("BackgroundJobRun");
            var httpClient = new HttpClient();

            var events = await services.Connection.GeofenceEvents.Where(x => !x.Reported).OrderBy(x => x.Date).ToListAsync();
            foreach (var e in events) 
            {
                if (!cancelToken.IsCancellationRequested)
                {
                    try 
                    {
                        var eventType = e.Entered ? "entered" : "exited";
                        var response = await client.PostAsync(Constants.SlackWebhook, new StringContent($"{{\"text\": \"Geofence {e.Key} {eventType}\"}}"), cancelToken);
                        response.EnsureSuccessStatusCode();
                        e.IsReported = true;
                        services.Connection.Update(e);
                    }
                    catch (Exception ex) 
                    {
                        // log it?
                    }
                }
            }
            return true;
        }
    }
}
```

**Comment by dahlbyk** [comment]
We'll try this out and reach out privately (gmail?) if we need additional assistance with our specific problem. Thanks for the nudge in the right direction!
