### ISSUE TITLE
Secure Settings

### ISSUE THREAD

**Issue by dansiegel** [shinyorg/shiny#230]
## Summary
There are many times in which I may have one or more settings which are of a more sensitive nature. For instance I may need to store a user token. For these scenarios we need a way to get Shiny to store settings using Secured Storage.

## API Changes

No real API changes should be made, however a Secure Settings Implementation should be added

```cs
services.UseSecureSettings();
```

## Intended Use Case
As discussed in the summary

**Comment by aritchie** [comment]
I was thinking of just building this on to the current settings

```csharp
ISettings.GetSecure<T>
ISettings.SetSecure
```

and for the bound appsettings model, you would simply mark values in the interface or implementation with [SecureAttribute]

Thoughts?

**Comment by dansiegel** [comment]
works for me

**Comment by dansiegel** [comment]
for context from #478

## API Changes
ISettings.Set(key, value, bool secure)?
[SecureAttribute] for binding?

**Comment by aritchie** [comment]
I've also consider making some sort of key/value binder with a store

```cs
IStore.Get<T>(key, defaultValue)
IStore.Set<T>(key, value)

class Stuff : INpc
{
   public string Property { get; set; } // left out npc
}

IBinder.Bind(npcObj, YourStore);

Stores could be:
Secure settings
OS Preferences
SQLite
etc
```

**Comment by dansiegel** [comment]
I do like that flexibility

**Comment by aritchie** [comment]
Part of the issue is that some of that is async based, so trying to decide how to go about it.  Maybe just a background flush that happens on a delay.

**Comment by dansiegel** [comment]
could also force this to run synchronously... async can be a problem when it comes to getters

**Comment by aritchie** [comment]
This work is now part of https://github.com/shinyorg/shiny/tree/feature/stores

**Comment by aritchie** [comment]
This has been released to preview

**Comment by Jerome-Liger** [comment]
Hi @aritchie,
I've migrate my Shiny ISettings (not secured in 1.x) to XamarinEssentials.SecureStorage... this is fine (all values are well secured in the com.company.product.xamarinessentials.xml Shared_prefs 👍 ) :
![2](https://user-images.githubusercontent.com/39192143/138266916-a32ad543-86d6-4c41-818a-c6c519a6ce41.png)

But my App is currently in production, and in the next version I'm currently developing, I need to (migrate the values, for the user don't loose his prefs with update, and then) "delete" my old Shiny.ISettings because this is an actual security breach... anyone can still read (with a rooted device and some advanced skills) the "Shiny.xml" values "in clear" that are still present :

![1](https://user-images.githubusercontent.com/39192143/138279313-346b4746-e6d0-4cf5-9ed0-47921cf3be3f.png)

I tried to directly delete my Keys/Values stored in Shiny.xml with the native way in Android OnCreate() :

```
using (var prefs = GetSharedPreferences("Shiny", FileCreationMode.Private))
{
    var editor = prefs.Edit();
    foreach (var pref in prefs.All)
    {
        if (pref.Key.Contains("Login") && pref.Value != null && pref.Value is string login)
            editor.Remove(pref.Key);
       [...]
    }
    //editor.Apply();
    editor.Commit();
}
```

But it doesn't work (maybe because Shiny is already locking this file cause "MainApplication : ShinyAndroidApplication <Startup>" has been loaded first ?)

I've tried another method, after Xamarin.Forms has been loaded, and with my previous "IShinyAppSettingsService" by removing all my keys :

```
var ShinySettingService = ShinyHost.Resolve<IShinyAppSettingsService>();
ShinySettingService.ClearUser();
```

And in my ShinyAppSettingsService implementation :

```
public void ClearUser()
{
    var props = TypeDescriptor.GetProperties(this)
        .Cast<PropertyDescriptor>()
        .Where(prop => !prop.IsReadOnly)
        .ToList();
    foreach (var prop in props)
        _settings.Remove($"{GetType().FullName}.{prop.Name}");
}
```

I've tried to help myself to understand with some "oldest Shiny code" I found there (I don't have access to 1.x code...) :
https://github.com/shinyorg/shiny/blob/9f624b16d8f4fefc538e35ae26ca9190955a3e3d/src/Shiny.Core/Stores/Platforms/Android/SettingsKeyValueStore.cs

But I don't understand why I'm unable to delete my "keys/values"... no error, but no action too... she Shiny.xml file is still present and readable with all my values in clear... :-(

And what is very weird, is that inside the Shiny.xml, it stores keys/values that are "named-based" on "XXX.**EssentialsSecureStorageService**.Keyname" and not my original Shiny service (XXX.**ShinyAppSettingsService**.Keyname)

![3](https://user-images.githubusercontent.com/39192143/138268714-82b1e679-8fe7-4a28-9855-3e4905c4ad0d.png)

I think Shiny and Essentials are working on each other and I don't understand why (and I cannot attach original source code to debug, so I'm a little blind ;-)).

Any idea or beginning of a way to help me ? I'm turning around since an entire day on this...

Thanks in advance (and sorry for "old deprecated code/version"... I unfortunately have no choice right now... next version of this app will be updated to Shiny.Framework ;-))

**Comment by Jerome-Liger** [comment]
@aritchie 
My bad... sorry for the inconvenience, the error came from my different services rename for migrating from ShinyAppSettingService to EssentialsSecureStorageService... I successfully fixed my own errors.

At least I learned a lot about the native behind-the-scenes of android preferences (Shiny and Essentials) ... it wasn't all wasted time ;-)
And I hope my explaination here can be helpfull to other people who will read this :-)

Thanks

**Comment by aritchie** [comment]
@Jerome-Liger please note that your questions are well outside of what I'm willing to offer via this project.  If you need help like this in the future, I do offer consulting.
