### ISSUE TITLE
Auto request permissions when starting a feature

### ISSUE THREAD

**Issue by aritchie** [shinyorg/shiny#335]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
As stated in the title.  This behaviour would coincide with the way Apple is treating some of their more modern APIs such as BLE

## API Changes
* JobManager.Schedule
* NotificationManager.Send
* GpsManager.StartListener, GetLastReading
* GeofenceManager.StartMonitoring
* BLE
* BeaconManager.StartMonitoring

What doesn't fit
* Motion Activity Manager - RequestAccess actually starts everything
* PushManager - RequestAccess actually returns the token

## Intended Use Case
Start the continual flow of people asking questions that don't understand mobile dev

**Comment by BaseCrusher** [comment]
Hello, I'm not sure if it would make sense to open a new Issue since it seams to fit very well here. 

I would suggest, that requesting the Bluetooth state on android should take Androids location permission into the equation. So that if you use Android and you check the permission status, it will return unautherized or something similar.

**Comment by aritchie** [comment]
@BaseCrusher It already does this.

**Comment by BaseCrusher** [comment]
Hmm, strangely enough it doesn't seem to work in my project.
When im doing a clean build so that the permissions are resetted and I check the Ble state it returns available eventhough I haven't given the app the location permission.

I'll try to reproduce it in a sample project tomorrow.

**Comment by aritchie** [comment]
This is basically done at this point
