### ISSUE TITLE
[Android] Notification GPS does not disappear after StopListener ()

### ISSUE THREAD

**Issue by HausBJB** [shinyorg/shiny#563]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

Hello
When I start the GPS listener I get a notification above that the service is running, which is correct.
As soon as I stop the GPS listener, the notification disappears briefly and reappears. What is actually not correct or do I see it wrong?

I know that this is a priview, it should only be used for information

With best regards
Peter

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x ] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [x ] Locations
 - [ ] HTTP Transfers
 - [x ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
2.0.0.2591

## Steps to Reproduce

```
     private async void StartGpsListener()
        {
            var manager = ShinyHost.Resolve<IGpsManager>();
            var result = await manager.RequestAccess(GpsRequest.Realtime(true));
            if (result == AccessState.Available)
            {
                await manager.StartListener(GpsRequest.Realtime(true));

                await Task.Delay(3000);
                await manager.StopListener();
            }

        }
```

![GPSListener](https://user-images.githubusercontent.com/53478848/114825948-20d7d300-9dc7-11eb-80de-d0237ad8cc00.gif)

**Comment by aritchie** [comment]
Ok - a couple of things - quit tweaking the template or the bot will close it. 

Second - please don't tell me to use it as info.  I need full bugs or I don't want them at all.  Remember, I'm not here to fix things for you as this is not a paid product nor are you a project sponsor which is why this statement holds true.  This bug is clear enough that I'm going to look into it.

**Comment by HausBJB** [comment]
Hello Allan,

1. Nobody ever said you need to fix bugs

2. Yes, this is not a paid product, but you are still the project manager and should also be interested in making your product error-free.

3. Why should I be a project sponsor when I will probably never use the product.

4. I thought Issus are there to report problems and not fix them


5. As we can see here, you have no interest in fixing the errors and write that is not an acceptable submission

https://github.com/shinyorg/shiny/issues/546

well, I really don't know what not to understand. The fact is the normal notification does not work on iOS.

And since this error should already be fixed here, the whole thing crashes now. If the StartListener is running foreground and then StopListener is called, but that is beneath it for you

```
 private async void StartGpsListener()
        {
            var manager = ShinyHost.Resolve<IGpsManager>();
            var result = await manager.RequestAccess(GpsRequest.Realtime(false));
            if (result == AccessState.Available)
            {
                await manager.StartListener(GpsRequest.Realtime(false));

                await Task.Delay(3000);
                await manager.StopListener();
            }

        }
```

I was always nice and polite and you were snotty and cheeky

**Comment by aritchie** [comment]
So you think your morally superior.... ok... allow me to educate you

1. You haven't been able to follow any of the project template instructions where it flat out says "beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!" - and then you have the audacity to tell me flat up - "use this as info".  So you are above my rules?

2. I spend an hour yesterday fixing a bug report that you made that did have enough info for (though you still didn't read the issue template instructions and the bot closed your issue).  I fixed the bug, ran it in the sample without issue.  Now you simply say "it crashes" with once again - NO stacktrace!

3. Notifications on iOS works just fine.  Your problem is that you didn't read the native docs on how notifications work on iOS, nor did you take the time to investigate what I had done.... hence why you didn't bother to include a stack trace for your issue - because there wasn't one.

So no.... you haven't been "nice and polite" at all!
