### ISSUE TITLE
Drop UWP?

### ISSUE THREAD

**Issue by aritchie** [shinyorg/shiny#632]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
No idea what the real future for UWP is.  I have never once used UWP in a professional setting, so it costs me time to support something I don't use.  Ultimately, I consider webassembly to be a much more appealing model than anything on windows at this point

Some of the options being considered are:
* Consider moving issues & feature requests to a sponsor only model
* Continue to offer it, but close down issues & feature requests for it
* Drop UWP 100% from source, focus on webassembly, android, & iOS

## API Changes
None

## Intended Use Case
Focus on other areas... consider WinUI long term if it proves itself.

**Comment by MKGNZ** [comment]
I use UWP all the time. It is easy to create a proof of concept and zip it up and send it to colleagues. 
Also supporting tools  (especially for Bluetooth)  are easy to create and share with UWP. 
Instead of going through the whole process of registering an app with Apple or Google and then adding test users so they can get a tool or a prototype that we don't know if it will be a real app it is too much hassle. Especially with Apple that the test user has to be a member of the company even though they don't need access to App store.  

My though is as long as Xamarin supports it it is easy to use it and reuse Xamarin libraries to use it.
With MAUI then whatever MAUI will supports for windows, UWP, WinUI, Flutter, ...

For webassembly a lot of companies don't like to use a browser, for security reasons, for apps that are internal or need speed (especially medical and financial).

**Comment by StanleyBroo** [comment]
If Windows is not supported? This is not interesting to me as I use Xamarin Forms just because we can create all apps in one go. The UWP app on the client is easy to distribute and appreciated from the LOB users ..continue their work on a bigger screen.
Working in a browser does not give the user the same experience or options.

**Comment by DDHSchmidt** [comment]
I can see where you're coming from. Ever since we started with Xamarin.Forms the UWP-support seems abysmal, even from Microsoft themselves. I'm hoping MAUI will switch the Windows target to WinUI, but infos regarding that are pretty ambiguous.

For the time being we're tied to UWP though and need the platform to be supported, including background tasks in our use case.
So yeah, UWP support would be sorely missed until we can migrate to greener pastures...

To be honest: We thought UWP support **was** already dropped, since the [Shiny.Support.UWP is already unlisted on NuGet](https://www.nuget.org/packages/Shiny.Support.Uwp) and this is a necessary package for UWP support, isn't it?

**Comment by aritchie** [comment]
@DDHSchmidt The way UWP is implemented has changed and is shown in the sample application within this repo.  That nuget package is no longer needed

**Comment by aritchie** [comment]
To anyone posting, I'm not interested in you losing interest in this library because I don't support UWP (unless you are a higher tier sponsor).  I'm more interested in the scenarios of what benefit it would be to all of us.  MKGNZ has given 2 good points that I consider "of value".  Please keep your posts relevant to this.

**Comment by aritchie** [comment]
I won't be dropping UWP, but support/issues for it are going to move to a sponsor only in the future
