### ISSUE TITLE
Cannot install Shiny nuget on latest Xamarin.Forms 5.0.0.2083 due to Xamarin.AndroidX.Lifecycle.LiveData conflict

### ISSUE THREAD

**Issue by kunjals** [shinyorg/shiny#663]
# PLEASE READ
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP

PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS
IF YOU HAVE AN ISSUE WITH DOCUMENTATION, DO NOT FILE AN ISSUE - PR'S ONLY!

## Feature Library

 - [ ] Core (Jobs, Settings, Initialization)
 - [ ] Locations (GPS, Geofencing, Motion Activity)
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] NFC
 - [ ] Push - Native
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase
 - [ ] Sensors
 - [ ] BluetoothLE Client
 - [ ] BluetoothLE Hosting
 - [ ] Beacons
 - [ ] SQLite Integration

## Version of Library
2.1.0.1769
## Steps to Reproduce
1. Create a new empty Xamarin Forms application.
2. Update Xamarin.Forms to latest 5.0.0.2083
3. Install-Package Shiny -Version 2.1.0.2769 on all head projects

## Expected Behavior
The Shiny nuget gets installed

## Actual Behavior
Install on Android is failing with the following stack trace:
Restoring packages for D:\Projects\ShinyBeacons\ShinyBeacons\ShinyBeacons.Android\ShinyBeacons.Android.csproj...
Install-Package : NU1107: Version conflict detected for Xamarin.AndroidX.Lifecycle.LiveData. Install/reference Xamarin.AndroidX.Lifecycle.LiveData 
2.3.0.1 directly to project ShinyBeacons.Android to resolve this issue. 
 ShinyBeacons.Android -> Shiny 2.1.0.2769 -> Shiny.Core 2.1.0.2769 -> Xamarin.AndroidX.Work.Runtime 2.5.0.1 -> Xamarin.AndroidX.Lifecycle.LiveData 
(>= 2.3.0.1) 
 ShinyBeacons.Android -> Xamarin.Forms 5.0.0.2083 -> Xamarin.AndroidX.Lifecycle.LiveData (>= 2.2.0.4 && < 2.3.0).
At line:1 char:1

I cannot directly add Xamarin.AndroidX.Lifecycle.LiveData 2.3.0.1 to the Android project because of this constraint Xamarin.Forms 5.0.0.2083 -> Xamarin.AndroidX.Lifecycle.LiveData (>= 2.2.0.4 && < 2.3.0).

**Comment by aritchie** [comment]
@kunjals Please note that this is not a bug to do with this library and I normally close these without an answer.  Since you're a sponsor, I'll take the time to point you in a direction.  

XF decided to set an upper bound on the version for AndroidX since there are often breaking changes on these libraries.  One of those dependencies is about 8 months old which is long for AndroidX.  Shiny needs newer versions of AndroidX to keep ahead of bugs with features like firebase.

That being said, this service release didn't include a lot of fixes - so I would check if you need it.  Second, if you decide you do need the update - the AndroidX fight is always going to be there.  You can easily fix this by manually editing the android projects and forcing the library version like this:

```xml
<PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData" Version="2.3.1" />
```
Obviously, you run the risk of breaking one library or the other, but that's the nature of the game
