### ISSUE TITLE
How to create a IHttpTransferManager object without prism?

### ISSUE THREAD

**Issue by ivoryguard** [shinyorg/shiny#75]
I want to upload a large file with Shiny HTTP.

I read  blog article, guide and looked shiny sample and then added shiny startup codes.

However, I have no idea how I can get IHttpTransferManager object reference at the following code;

```
public CreateViewModel(INavigationService navigationService,
					   IHttpTransferManager httpTransfers,
					   IUserDialogs dialogs,
					   IFileSystem fileSystem,
					   AppSettings appSettings)
```
					   
When I debug Shiny sample, the type of httpTransfers is {Shiny.Net.Http.HttpTransferManager} and it may be created in Platform project and injected into Shared project assembly.
(Shiny.Net.Http.HttpTransferManager cannot be created in .NET Standard project.)

I did not find any explicit object creation code or exlicit dependency injection definition for IHttpTransferManager at Shiny Sample.

My app code is based on default XF forms template. So I may create a IHttpTransferManager object or get the reference and pass it into my ViewModel class.

How I can encue upload item in IHttpTransferManager and link progress changed event?

Best regards.

**Comment by ivoryguard** [comment]
According to your documentation and sample, Prism may be required to inject IHttpTransferManager to ViewModel. Your source does not define the attributes for Xamarin Dependency Service and I cannot use it for DI.

**Comment by aritchie** [comment]
Please note, this is not a support site.  I'm still working on documentation because this is a beta library.  My bot is consistently closing these issues on you because you aren't following the template because the templates are very well defined.  So no more please... you can wait for docs or figure things out.  

This library does not take any dependencies on Xamarin Forms, Prism, or RXUI as I've already stated and as you can see in the nuget package itself.  

> I did not find any explicit object creation code or explicit dependency injection definition for IHttpTransferManager at Shiny Sample.

https://github.com/shinyorg/shinysamples/blob/master/Samples/ShinySetup/SampleStartup.cs#L43

> According to your documentation and sample, Prism may be required to inject IHttpTransferManager to ViewModel. Your source does not define the attributes for Xamarin Dependency Service and I cannot use it for DI.

ShinyHost.Resolve is what you need and is the equivalent of the DependencyService in XF.
