### ISSUE TITLE
Documentation - Notifications

### ISSUE THREAD

**Issue by aritchie** [shinyorg/shiny#82]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
Write the docs for Shiny.Notifications

## API Changes
None

## Intended Use Case
None

**Comment by tentom** [comment]
Hi, I have been using your BluetoothLE plugin before and I am now migrating to Shiny and starting to use more of the functionality.

I saw that this issue was closed and that there was no "help wanted" tag on the issue. 
Does this mean that you have some documentation laying around someplace else than in the master and develop branches?

I have forked the project and have written some documentation primarily for my self, but if there is no more documentation i would be happy to share what I have.

**Comment by aritchie** [comment]
@tentom Doc additions are always welcome.  At the time, notifications was being updated quite heavily and thus was not marked appropriately
