### ISSUE TITLE
Support requesting the bluetooth PHY connection speed

### ISSUE THREAD

**Issue by ianewby** [shinyorg/shiny#833]
### Summary

There is no way currently in Shiny to set the Bluetooth PHY, this stops both the bluetooth long range PHY and the faster 2mb connection speed from being used.

### API Changes

Add method to GattCharacteristic to request a different PHY level.

### Intended Use Case

Allow increased range or throughput on bluetooth connections, depending on requirements

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
This only applies to Android at the moment.  It is automatic on iOS and Android only requires a few flags to be set.  I'll consider how to open this up with native settings on v3 of the library.

I'm going to close this since there isn't anything in the "API changes" to make it worthwhile tracking at the moment.  This layer exists on the actual peripheral/device portion of the android API in any case.
