### ISSUE TITLE
[Bug]: Reading a Characteristic on iOS doesn't clears the char buffer

### ISSUE THREAD

**Issue by bluekuen** [shinyorg/shiny#944]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What platform(s) are effected?

- [X] iOS 12
- [X] iOS 13
- [X] iOS 14
- [X] iOS 15
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [ ] Android 12
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

Read a readable Characteristic on iOS

### Expected Behavior

Characteristic is read and buffer is cleared 

### Actual Behavior

Characteristic buffer doesn't get cleared so that the next time the arrays content contains the same array plus the new one until 200 bytes length is reached.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Ok enough is enough.  This is becoming an unnecessary support buffer at this point.  Issues like this and the #938 are a complete waste of my time!  This issue doesn't make ANY sense.  There is no reproducible sample, let alone code sample.

It's clear you've been using my OSS for a couple of years, you've sent multiple issues where only 1 has lead to an actual bug, so.... this needs to change.  You need to be more respectful with my time, perhaps even consider becoming a sponsor at the very least.

**Comment by bluekuen** [comment]
Apoligies! I am a little stressed out these days! It's just so that it was running before with the ACR.BluetoothLE Plugin and is still running on Android with the new shiny project. I just don't get it why it's not working on iOS anymore.
 I'm asking my boss if we could sponsor you, it's definetly appropriate as we're using your plugin since several years now, that's correct.

**Comment by bluekuen** [comment]
I just applied for 50$ monthly subscription. It just has to get through our accounting.
But can you tell me before where i can get help with the library? 
I still couldn't figure out why my read data from my readCharacteristic on iOS only gives me 200 bytes instead of 316 like on Android. 
That would be really kind of you! 
Thanks for the great lib!

**Comment by aritchie** [comment]
I can appreciate that you are stressed, but this wasn't meant as a support forum because this isn't a product.  The library with full source code is given away for free, my time is not.  If you have bugs, you need to file FULL reproducible cases and take the time to explain the issue.  

What you need is consultancy because it sounds like you have key gaps in knowledge working with BLE (ie. 16bit UUIDs, MTU, etc).  The sponsorship is meant as a "I have tons of questions about the library or I love the library "keep it going".  It isn't meant as a support contract, nor is it meant for explaining the underlying technology.  

Your issue is that you are assuming an MTU greater than 20 bytes.  You will often get higher MTU's but it it isn't arbitrary.  You should be streaming data in packets and not assuming the full payload hits your phone in one shot.  Shiny has a RequestMTU function, but it is only relevant on Android and the request size you make, still isn't guaranteed.
