### ISSUE TITLE
[Feature Request]: Add a NotifyBlob method

### ISSUE THREAD

**Issue by rhinohq** [shinyorg/shiny#962]
### Summary

The ability to use a 'NotifyBlob' method in the Shiny.BluetoothLE.Hosting library that acts like the 'WriteBlob' method in the Shiny.BluetoothLE library. 

'Used for sending larger arrays or streams of data without working with the MTU byte gap'

### API Changes

1 new method: NotifyBlob(byte[] data, params IPeriperal[] centrals)

### Intended Use Case

For keeping data transmission code consistent whether sending from a Client or Server.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
I'm sorry, but this is definitely not going to be happening.

On the client, WriteBlob has some purpose in that you can connect to an IOT device that will (never) stop broadcasting.  BLE Hosting on mobile is a different story as there are many ways that streams can be cut due to many things a) app backgrounding b) battery issues  c) connectivity issues etc. 

The big issue would be sending out potentially large chunks of data to multiple clients and making it hard to tell progress across those clients, if one client misses a packet, do all wait in line, do all blob sends fail, do I track different locations based on each client... who knows...  not something I want to get into

Server and client services run vastly different in so many circumstances that keeping them consistent also isn't a great argument for this use-case.  

Lastly, while WriteBlob is part of the client, I still have an issue with it.  BLE at least as far as GATT which is the protocol the libraries conform to, was meant for signals - not large sets of data.  Even larger MTU's on GATT are usually 250-280 bytes on average, is still way too tiny for large sets of data.

**Comment by rhinohq** [comment]
Understood. Thanks for your response.

How might one retrieve the following values in order to handle this manually?

- The MTU size of a client IPeripheral from the Hosting code 
- The MTU size of the Hosting server

**Comment by aritchie** [comment]
It isn't currently provided by the library and I'm not even sure android gives out that detail

**Comment by rhinohq** [comment]
https://github.com/shinyorg/shiny/pull/970

Adding link to pull request for this work as reference for people in the future.
